### ISSUE TITLE
Ignore -git suffixes?

### ISSUE THREAD

**Issue by clintval** [simon04/aur-out-of-date#1]
Thanks for this! Just gave it a try on my own packages `-u clintval`.

I wonder if you might change the status of any package with a `-git` suffix as they are not necessarily out-of-date. They could demand maintainer attention if left for too long so maybe a special status for these packages?

**Comment by simon04** [comment]
Thanks for giving the tool a try. 😄 

What skipping over `-git`, `-hg`, `-svn` packages unless the flag `-devel` is specified on the command line?

**Comment by clintval** [comment]
Sure that sounds like a good plan!

Another option would be to save reporting all CVS-upstream packages until the end of your `stdout` report so they are logically grouped.

**Comment by simon04** [comment]
Thanks for the suggestion and ideas! I implemented a `-devel` flag and released it as 0.6.0. Have fun! 😄
