### ISSUE TITLE
Unable to detect updates for some github packages with -devel

### ISSUE THREAD

**Issue by maximbaz** [simon04/aur-out-of-date#18]
I'm using `-devel` so I'd expect to get versions for all of the packages below (because all of them are hosted on github), however most of the packages end up with the UNKNOWN state. Why?

The problem is not with `-local`, with `-pkg` I experience the same issue.

![image](https://user-images.githubusercontent.com/1177900/38162502-8730e2be-34e2-11e8-81ce-65d66939a74b.png)

For `alacritty-git`, the expected result would be `0.1.0.760.g3d75c49-1` (because current latest commit on master is [3d75c49](https://github.com/jwilm/alacritty/commit/3d75c491912952d2a18fb34ab81221b1bded07d5)).

**Comment by maximbaz** [comment]
Judging by this code, when using `-local` I don't even have to provide `-devel`, and the tool should still correctly distinguish the vcs packages and get their proper versions:

https://github.com/simon04/aur-out-of-date/blob/80f1d8e9a6c6311d6dc43817a0af8e6ecf5dc711/main.go#L139-L142

But why is it looking at the releases, and not at the latest commits? Is it a bug, or intentional design?

---

To give you some context, we want to integrate your tool in `aurutils` with one main purpose: we give `aur-out-of-date` the list of local `.SRCINFO` paths to VCS packages, and expect to get their latest versions for these packages.

So, continuing to use `alacritty-git` as an example, we would like `aur-out-of-date` to query Github API to get the latest commit hash ([3d75c49](https://github.com/jwilm/alacritty/commit/3d75c491912952d2a18fb34ab81221b1bded07d5)), process the [pkgver()](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alacritty-git) function and return the message "alacritty-git" corresponding version, in this case `0.1.0.760.g3d75c49-1`.

Would this be possible to achieve?

**Comment by simon04** [comment]
Well, this is outside of the scope I have in mind for aur-out-of-date (being a tool to determine new _releases_ for package _maintainers_). In fact, little is present in the codebase at the moment w.r.t. obtaining the latest Git commit, obtaining the `PKGBUILD`, evaluating the shell function `pkgver`.

**Comment by maximbaz** [comment]
That's what I thought too once I got a little closer with the codebase.

What is the `-devel` option though, what is it supposed to do?

**Comment by simon04** [comment]
The option `-devel` runs the version check also on the svn/hg/git packages, i.e., determines whether released version is newer (according to [`pacman(8)`](https://www.archlinux.org/pacman/pacman.8.html)) than the packaged version. 

If `alacritty` used [GitHub releases](https://github.com/jwilm/alacritty/releases), a `0.1.1` or `0.2.0` or `2.0.0` release would be determined newer than the package version `0.1.0.760.g3d75c49-1`.

**Comment by maximbaz** [comment]
Aaah, so it still looks at the releases, but not at the actual commit hashes? Just so that I understand, how is this used by maintainers, I thought the whole point of `-git` packages was to not follow the releases? Is it needed to catch potential changes between major versions in how an app should be built?

**Comment by simon04** [comment]
The idea is that after a major version jump, the package script may need to be adapted.

**Comment by maximbaz** [comment]
Understood, thank you for the explanation.
