### ISSUE TITLE
Doesn't work on some Github sources

### ISSUE THREAD

**Issue by sum01** [simon04/aur-out-of-date#19]
```
[UNKNOWN] [python-cmake-format] No GitHub release found for https://github.com/cheshirekow/cmake_format/archive/v0.3.6.tar.gz 
[UNKNOWN] [rocketchat-desktop] No GitHub release found for https://github.com/RocketChat/Rocket.Chat.Electron/archive/2.10.5.tar.gz 
```
I have other Github PKGBUILD's on the AUR that this works for just fine, but these specifically don't work for whatever reason. Rocketchat-desktop has Github releases, and cmake_format has tags.

---

Unreleated, and I know you don't list it as supported, but could you support Rubygems?

`[UNKNOWN] [ruby-htmlbeautifier] No release found for https://rubygems.org/downloads/htmlbeautifier-1.3.1.gem `

**Comment by simon04** [comment]
The bug regarding `rocketchat-desktop` is fixed; dots in repository names had not been supported.

The project `python-cmake-format` only publishes [Git tags](https://api.github.com/repos/cheshirekow/cmake_format/tags), but no [releases](https://api.github.com/repos/cheshirekow/cmake_format/releases/latest). Currently, only the latter are fetched and considered.

**Comment by sum01** [comment]
Could it fall back to tags if no releases are found?
