### ISSUE TITLE
Something about ombi versions on github aren't seen as out of date

### ISSUE THREAD

**Issue by fryfrog** [simon04/aur-out-of-date#21]
```
[UP-TO-DATE] [ombi] Package ombi 3.0.3268-1 matches upstream version Ombi v3.0.3304
```
https://github.com/tidusjar/Ombi/releases

Maybe the long final version, .3268 vs .3304? Maybe the "v"? :/

**Comment by fryfrog** [comment]
It must be the "v", I just realized libite has the same issue:

```
[UP-TO-DATE] [libite] Package libite 2.0.1-1 matches upstream version Libite (-lite) v2.0.2
```

**Comment by simon04** [comment]
This has been fixed in https://github.com/simon04/aur-out-of-date/commit/1b8321edd83b31c2e498fc8323563d90fb291721 and https://github.com/simon04/aur-out-of-date/commit/7fcf263e9073c6465dee31369eb8fe0be5aa8bb6.
