### ISSUE TITLE
Access to github gets blocked because of API limit rate

### ISSUE THREAD

**Issue by goggle** [simon04/aur-out-of-date#27]
After trying out this software for a while, I get the following error message for all github sources:
```
aur-out-of-date -user frealgagu

[UNKNOWN] [antimicro][2.23-3] Failed to obtain GitHub release for AntiMicro/antimicro from https://api.github.com/repos/AntiMicro/antimicro/releases/latest: API rate limit exceeded for 131.218.111.118. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
...
```
It seems as though github blocks the access because of too many requests... Isn't there a better way to access the github content, so that this limitations doesn't get triggered so fast?

**Comment by simon04** [comment]
This is covered in the README: https://github.com/simon04/aur-out-of-date#principle
