### ISSUE TITLE
b2sums is not a invalid variable

### ISSUE THREAD

**Issue by thezoorat** [simon04/aur-out-of-date#40]
when i run ` aur-out-of-date -local .SRCINFO ` on https://aur.archlinux.org/packages/edex-ui-bin/
output is 
```
panic: Failed to parse .SRCINFO: invalid variable: b2sums

goroutine 1 [running]:
main.handlePackages(0xc000012100, 0x0, 0x0, 0x0, 0x7a5680, 0xc000028680)
	main.go:69 +0x431
main.main()
	main.go:133 +0xa48
```

but when i run ` makepkg --printsrcinfo > .SRCINFO `
the **.SRCINFO** file is unchanged 

so **b2sums is a valid variable**

**Comment by simon04** [comment]
Pacman commit: https://git.archlinux.org/pacman.git/commit/?id=e03752e6adc86cbb4cb4f52a38f6e3e98cbe9dd5

Support to the goPKGBUILD library has been added via https://github.com/mikkeloscar/gopkgbuild/commit/2582c34596c645c672665815a75e3fefe45ff01d

I've released version [3.1.0](https://github.com/simon04/aur-out-of-date/releases/tag/v3.1.0)
