### ISSUE TITLE
Exclude GitHub pre-releases

### ISSUE THREAD

**Issue by simon04** [simon04/aur-out-of-date#9]
Releases such as https://github.com/stumpwm/stumpwm/releases/tag/v1.0.1-rc, https://github.com/webpack/webpack/releases/tag/v4.0.0-beta.3, or https://github.com/ariya/phantomjs/releases/tag/2.1.3 should be excluded.

The [releases Atom feed](https://github.com/ariya/phantomjs/releases.atom) does not provide this information, but the [releases API](https://api.github.com/repos/ariya/phantomjs/releases) does. The latter however, is subject to [rate limiting](https://developer.github.com/v3/#rate-limiting) (60 unauthenticated request per hour).

**Comment by AdamSLevy** [comment]
I wrote about this on the mailing list. This would be a nice feature! 

I also wrote the following:
"It might be worth adding an option to ignore version tags that end in 'rc*'. Or perhaps make that the default and add a flag to *not* ignore release candidate tags. I'm sure there are other conventions for post-fixes on version tags that indicate pre release or testing status. Maybe a more flexible way to go would be to offer an environment variable or option for setting a list of regexes to disregard if matched."

**Comment by AladW** [comment]
An alternative would be #11, where the user could filter out `rc` releases programatically with little effort.

**Comment by AdamSLevy** [comment]
That would technically solve the filtering issue but it's admittedly not very convenient from a UI perspective. It would be good for a script that automatically runs to kick off some notification. But writing a wrapper to give me what I want from your program as described in #11 would still require me to re-format the output. The current text output is nice and readable and useful. Having a way to configure your program to ignore versions matching a pattern would be nice but this might be bikeshedding. Especially considering that the user can read and see for themselves what the full version string is.

**Comment by kewlfft** [comment]
why not using the API? there is a pre-release flag that can be tested, for example you can see in this example that `1.5.0` was a pre-release and we would have disregarded it.
https://api.github.com/repos/aladw/aurutils/releases

**Comment by kewlfft** [comment]
The API solution seems to be the cleanest and for personal maintenance of ones packages the 60 API request limit per hour should not be an issue. I am developing a similar tool in *Python* (I did not know about your project unfortunately) and may use the API. 

Do you know why https://api.github.com/repos/ariya/phantomjs/releases is only showing the 2 prereleases and not the stable releases before?

**Comment by yan12125** [comment]
Yesterday I got 3 out-of-date notifications, and 2 of them are false positives - GitHub pre-releases.

```
Your package logcat-color [1] has been flagged out-of-date by kewl [2]:

Version 0.7.0preview is out. #simon04/aur-out-of-date
```
```
Your package phantomjs [1] has been flagged out-of-date by kewl [2]:

Version 2.1.3 is out. #simon04/aur-out-of-date
```

Implementing this feature should definitely save people from wasting time.

Currently I'm using [nvchecker](https://github.com/lilydjwg/nvchecker). It supports either [checking tags or the latest release](https://github.com/lilydjwg/nvchecker#check-github) (excluding pre-releases, of course).

From https://github.com/simon04/aur-out-of-date/issues/9#issue-300133173:

> The latter however, is subject to rate limiting (60 unauthenticated request per hour).

I can pass my GitHub token to nvchecker via ```$NVCHECKER_GITHUB_TOKEN```, which is quite handy. I guess aur-out-of-date can do the same thing.

A better solution for phantomjs is don't checking it as that project is [practically dead](https://github.com/ariya/phantomjs/issues/15344). nvchecker supports [per-package settings](https://github.com/lilydjwg/nvchecker#version-source-files), so it's easy to pick only the packages you want.

**Comment by kewlfft** [comment]
@yan12125 Sorry about the unjustified notifications, I am the one to blame, I was testing the tool and had not realized about this issue.
Thanks for the suggestion, it seems indeed easy to authenticate with basic auth or OAuth and lift the limit. The limit at 60 should allow regular use of the average user and I think it is not bad that additional setting is required to go beyond this limit:
* running it for hundreds of packages is putting some load on the servers, better to make sure people understand what they do
* this is limited to a handful of users, maintaining hundreds of packages or maintaining the AUR,

**Comment by yan12125** [comment]
Is this _really_ fixed? I got another out-of-date flag 12 minutes ago.
```
Your package phantomjs [1] has been flagged out-of-date by simon04
[2]:

Version 2.1.3 is out. #simon04/aur-out-of-date
```
And you _should_ check AUR comments manually before flagging. Using robots to flag packages is wrong and annoying.

**Comment by simon04** [comment]
https://aur.archlinux.org/packages/phantomjs/ uses https://github.com/ariya/phantomjs as source, and https://github.com/ariya/phantomjs/releases lists 2.1.3 as latest release (without pre-release or draft status). IMO the tool works correctly.

**Comment by yan12125** [comment]
Sorry, not checking it again before posting. It's beyond my expectation that things are changed in two days.

But still, it's better to check comments at https://aur.archlinux.org/packages/phantomjs for why this package is stuck to 2.1.1 before flagging it.
